// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AvatarFrame 是头像框（服务端下发的是图片地址 + 相对头像边长的位置参数）。
 * 
 * 换算公式与手机版 AvatarFrame 一致：框边长 = 头像边长 × scale，
 * 横/纵向位移 = 头像边长 × offset / 100。
 */
export class AvatarFrame {
    "key"?: string;
    "name"?: string;
    "imageUrl"?: string;
    "scale"?: number;
    "offsetX"?: number;
    "offsetY"?: number;

    /** Creates a new AvatarFrame instance. */
    constructor($$source: Partial<AvatarFrame> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvatarFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): AvatarFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvatarFrame($$parsedSource as Partial<AvatarFrame>);
    }
}

/**
 * ChatEmoji 是一个本站表情。
 */
export class ChatEmoji {
    "name": string;
    "url": string;

    /** Creates a new ChatEmoji instance. */
    constructor($$source: Partial<ChatEmoji> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatEmoji instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatEmoji {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatEmoji($$parsedSource as Partial<ChatEmoji>);
    }
}

/**
 * ChatGroup 是一个群聊。
 */
export class ChatGroup {
    "id": string;
    "name": string;
    "description"?: string;
    "avatar"?: string;

    /**
     * Icon 是群的 emoji 图标（手机版 GroupInfo.icon，默认 🏛）。
     */
    "icon"?: string;

    /**
     * Type 是群类型：chat=聊天室、notice=公告版（全体禁言，仅管理员可发言）。
     */
    "type"?: string;

    /**
     * MemberRole 是当前用户在该群的角色：admin / member。
     */
    "memberRole"?: string;
    "memberCount": number;
    "onlineCount": number;
    "unreadCount": number;

    /** Creates a new ChatGroup instance. */
    constructor($$source: Partial<ChatGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("memberCount" in $$source)) {
            this["memberCount"] = 0;
        }
        if (!("onlineCount" in $$source)) {
            this["onlineCount"] = 0;
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatGroup($$parsedSource as Partial<ChatGroup>);
    }
}

/**
 * ChatMessage 是一条聊天消息（私聊或群聊共用）。
 */
export class ChatMessage {
    "id": string;
    "senderId"?: string;
    "senderUid": number;
    "senderName"?: string;
    "senderAvatar"?: string;
    "receiverId"?: string;
    "groupId"?: string;
    "content": string;
    "msgType": string;
    "createdAt"?: string;
    "isMine": boolean;
    "replyToId"?: string;

    /**
     * 群聊里服务端可能会带上被回复的消息摘要
     */
    "replyPreview"?: string;

    /**
     * ===== 群聊专属字段（对齐手机版 GroupMessage）=====
     * SenderIsAdmin / SenderLevel / SenderNameColor / SenderFrame 只由群聊历史与
     * 轮询接口下发；私聊拿不到（手机版私聊也不画这些装饰）。
     */
    "senderIsAdmin"?: boolean;
    "senderLevel"?: number;
    "senderNameColor"?: string;
    "senderFrame"?: AvatarFrame | null;

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("senderUid" in $$source)) {
            this["senderUid"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("msgType" in $$source)) {
            this["msgType"] = "";
        }
        if (!("isMine" in $$source)) {
            this["isMine"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        const $$createField16_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("senderFrame" in $$parsedSource) {
            $$parsedSource["senderFrame"] = $$createField16_0($$parsedSource["senderFrame"]);
        }
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

/**
 * Friend 是好友列表里的一项。
 */
export class Friend {
    "id": string;
    "uid": number;
    "nickname": string;
    "avatar"?: string;
    "signature"?: string;

    /**
     * Status：online / away / offline（服务端按心跳时间判定，90s 内 online，
     * 90~300s away，超过 300s offline）
     */
    "status"?: string;

    /**
     * Activity 是「正在玩：xxx」，对方关闭分享时为空
     */
    "activity"?: string;
    "note"?: string;
    "lastMessage"?: string;
    "lastMessageAt"?: string;
    "unreadCount": number;

    /** Creates a new Friend instance. */
    constructor($$source: Partial<Friend> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("uid" in $$source)) {
            this["uid"] = 0;
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Friend instance from a string or object.
     */
    static createFrom($$source: any = {}): Friend {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Friend($$parsedSource as Partial<Friend>);
    }
}

/**
 * FriendList 是好友列表 + 待处理申请数。
 */
export class FriendList {
    "friends": Friend[];
    "pendingRequests"?: FriendRequest[];
    "pendingCount": number;

    /** Creates a new FriendList instance. */
    constructor($$source: Partial<FriendList> = {}) {
        if (!("friends" in $$source)) {
            this["friends"] = [];
        }
        if (!("pendingCount" in $$source)) {
            this["pendingCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendList instance from a string or object.
     */
    static createFrom($$source: any = {}): FriendList {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("friends" in $$parsedSource) {
            $$parsedSource["friends"] = $$createField0_0($$parsedSource["friends"]);
        }
        if ("pendingRequests" in $$parsedSource) {
            $$parsedSource["pendingRequests"] = $$createField1_0($$parsedSource["pendingRequests"]);
        }
        return new FriendList($$parsedSource as Partial<FriendList>);
    }
}

/**
 * FriendRequest 是一条待处理的好友申请。
 */
export class FriendRequest {
    "friendshipId": string;
    "uid": number;
    "nickname": string;
    "avatar"?: string;
    "signature"?: string;
    "createdAt"?: string;

    /** Creates a new FriendRequest instance. */
    constructor($$source: Partial<FriendRequest> = {}) {
        if (!("friendshipId" in $$source)) {
            this["friendshipId"] = "";
        }
        if (!("uid" in $$source)) {
            this["uid"] = 0;
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): FriendRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FriendRequest($$parsedSource as Partial<FriendRequest>);
    }
}

/**
 * UserProfile 是用户资料页的数据（GET /user/profile）。
 * 
 * 字段名与手机版 renderUserProfile 的读取保持一致（avatarUrl / totalGames /
 * totalPlayTime / activity）。
 */
export class UserProfile {
    "uid": number;
    "nickname": string;
    "signature"?: string;
    "avatar"?: string;
    "status"?: string;
    "activity"?: string;
    "totalGames": number;
    "totalPlayTime": number;

    /**
     * Level 是社区等级（手机版资料页在昵称旁挂 Lv.N 徽章）。
     */
    "level": number;

    /**
     * FriendSince 是「成为好友」的时间文案（服务端可能直接下发格式化结果）。
     */
    "friendSince"?: string;

    /**
     * FriendStatus：accepted（已是好友）/ pending（申请中）/ none。
     * FriendDirection 仅在 pending 时有意义：received（对方申请我）/ sent。
     */
    "friendStatus"?: string;
    "friendDirection"?: string;
    "recentGames"?: UserRecentGame[];
    "frame"?: AvatarFrame | null;

    /**
     * PlayingGame / PlayingStartedAt 是「正在玩」的结构化形式。
     * 
     * 服务端当前只下发 activity 这一句拼好的文案（"正在玩：xxx"），没有开始
     * 时间，客户端算不出「已玩多久」。这两个字段先按别名列表预留：服务端补上
     * 之后资料卡立刻能显示实时时长，不需要再改客户端。
     */
    "playingGame"?: string;
    "playingStartedAt"?: number;

    /** Creates a new UserProfile instance. */
    constructor($$source: Partial<UserProfile> = {}) {
        if (!("uid" in $$source)) {
            this["uid"] = 0;
        }
        if (!("nickname" in $$source)) {
            this["nickname"] = "";
        }
        if (!("totalGames" in $$source)) {
            this["totalGames"] = 0;
        }
        if (!("totalPlayTime" in $$source)) {
            this["totalPlayTime"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UserProfile {
        const $$createField12_0 = $$createType7;
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentGames" in $$parsedSource) {
            $$parsedSource["recentGames"] = $$createField12_0($$parsedSource["recentGames"]);
        }
        if ("frame" in $$parsedSource) {
            $$parsedSource["frame"] = $$createField13_0($$parsedSource["frame"]);
        }
        return new UserProfile($$parsedSource as Partial<UserProfile>);
    }
}

/**
 * UserRecentGame 是资料页「最近游玩」里的一条。
 */
export class UserRecentGame {
    "title": string;
    "playTime": number;
    "lastPlayedAt": number;

    /** Creates a new UserRecentGame instance. */
    constructor($$source: Partial<UserRecentGame> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("playTime" in $$source)) {
            this["playTime"] = 0;
        }
        if (!("lastPlayedAt" in $$source)) {
            this["lastPlayedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserRecentGame instance from a string or object.
     */
    static createFrom($$source: any = {}): UserRecentGame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserRecentGame($$parsedSource as Partial<UserRecentGame>);
    }
}

// Private type creation functions
const $$createType0 = AvatarFrame.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Friend.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FriendRequest.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = UserRecentGame.createFrom;
const $$createType7 = $Create.Array($$createType6);
