// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService 是 YukiHub 自建账号（yukihub.zh.kg）在桌面端的入口：
 * 登录 / 注册 / 资料、云同步游戏库、在线状态，以及好友与聊天。
 * 
 * 登录与云同步之所以放在同一个服务里：它们共用一份访问令牌，
 * 而令牌的刷新要集中处理（多处各自刷新会互相顶掉）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as yukihubaccount$0 from "./yukihubaccount/models.js";

/**
 * AcceptFriendRequest 接受好友申请。
 */
export function AcceptFriendRequest(friendshipID: string, uid: number): $CancellablePromise<void> {
    return $Call.ByID(180565005, friendshipID, uid);
}

/**
 * GetAccountLevel 查询等级 / 经验 / 签到状态。
 */
export function GetAccountLevel(): $CancellablePromise<vo$0.AccountLevel> {
    return $Call.ByID(81280639).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetAccountStatus 返回当前账号状态（不含令牌）。
 */
export function GetAccountStatus(): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(1825179945).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetChatHistory 拉与某人的历史消息。
 */
export function GetChatHistory(friendID: string, offset: number, limit: number): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(1025797374, friendID, offset, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetChatUnreadCount 未读消息总数。
 */
export function GetChatUnreadCount(): $CancellablePromise<number> {
    return $Call.ByID(2745218308);
}

/**
 * GetGroupHistory 群历史消息。
 */
export function GetGroupHistory(groupID: string, offset: number, limit: number): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(1169809469, groupID, offset, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListChatEmojis 本站表情列表。
 */
export function ListChatEmojis(): $CancellablePromise<yukihubaccount$0.ChatEmoji[]> {
    return $Call.ByID(4088162309).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListChatGroups 群列表。
 */
export function ListChatGroups(): $CancellablePromise<yukihubaccount$0.ChatGroup[]> {
    return $Call.ByID(2834922682).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListFriends 好友列表与待处理申请。
 */
export function ListFriends(): $CancellablePromise<yukihubaccount$0.FriendList> {
    return $Call.ByID(138003445).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * LoginAccount 用邮箱 + 密码登录。
 */
export function LoginAccount(email: string, password: string): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(3439494088, email, password).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LogoutAccount 退出登录：清本地会话、停心跳、尽力通知服务端下线。
 */
export function LogoutAccount(): $CancellablePromise<void> {
    return $Call.ByID(1118106453);
}

/**
 * PollChatMessages 拉新消息（前端每 10 秒调一次，与手机版一致）。
 */
export function PollChatMessages(afterID: string, friendID: string, peek: boolean): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(3275711423, afterID, friendID, peek).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PollGroupMessages 拉群新消息。
 */
export function PollGroupMessages(groupID: string, afterID: string): $CancellablePromise<yukihubaccount$0.ChatMessage[]> {
    return $Call.ByID(3718523948, groupID, afterID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RegisterAccount 用邮箱 + 验证码注册并直接进入登录状态。
 */
export function RegisterAccount(email: string, password: string, nickname: string, code: string): $CancellablePromise<vo$0.AccountStatus> {
    return $Call.ByID(586367668, email, password, nickname, code).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RejectFriendRequest 拒绝好友申请。
 */
export function RejectFriendRequest(friendshipID: string): $CancellablePromise<void> {
    return $Call.ByID(282440252, friendshipID);
}

/**
 * RemoveFriend 删除好友。
 */
export function RemoveFriend(friendID: string): $CancellablePromise<void> {
    return $Call.ByID(2457191756, friendID);
}

/**
 * ResetAccountPassword 用邮箱验证码重置密码。
 */
export function ResetAccountPassword(email: string, code: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3688801563, email, code, password);
}

/**
 * SearchUsers 搜用户。
 */
export function SearchUsers(keyword: string): $CancellablePromise<yukihubaccount$0.Friend[]> {
    return $Call.ByID(865387128, keyword).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SendAccountCode 发送邮箱验证码。purpose 传 "register"（默认）或 "reset"。
 */
export function SendAccountCode(email: string, purpose: string): $CancellablePromise<void> {
    return $Call.ByID(3958706468, email, purpose);
}

/**
 * SendChatMessage 发私聊消息。
 */
export function SendChatMessage(receiverID: string, content: string, msgType: string, replyToID: string): $CancellablePromise<yukihubaccount$0.ChatMessage> {
    return $Call.ByID(2333574947, receiverID, content, msgType, replyToID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SendFriendRequest 发好友申请。
 */
export function SendFriendRequest(target: string): $CancellablePromise<void> {
    return $Call.ByID(2174757163, target);
}

/**
 * SendGroupMessage 发群消息。
 */
export function SendGroupMessage(groupID: string, content: string, msgType: string, replyToID: string): $CancellablePromise<yukihubaccount$0.ChatMessage> {
    return $Call.ByID(2435495340, groupID, content, msgType, replyToID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetAccountCloudSyncEnabled 开关「登录后自动同步」。
 */
export function SetAccountCloudSyncEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3584650856, enabled);
}

/**
 * SetAccountSharePlaying 开关「向好友展示正在玩的游戏」。
 */
export function SetAccountSharePlaying(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1073884660, enabled);
}

/**
 * SetFriendNote 设置好友备注。
 */
export function SetFriendNote(friendID: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(1775097840, friendID, note);
}

/**
 * SyncAccountNow 立刻与云端同步一次游戏库。
 * 
 * 上传方向复用 YukiHubExporter（产出的就是 Android 侧 schema 5 快照，
 * 与手机版 `/sync/upload` 收的格式完全相同）；下载方向复用 YukiHubImporter。
 */
export function SyncAccountNow(): $CancellablePromise<vo$0.AccountSyncResult> {
    return $Call.ByID(2194510418).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * TestAccountConnection 探测账号服务是否可达（邮箱界面上的「测试连接」）。
 */
export function TestAccountConnection(): $CancellablePromise<void> {
    return $Call.ByID(3337605335);
}

/**
 * UpdateAccountNickname 修改云端昵称。
 */
export function UpdateAccountNickname(nickname: string): $CancellablePromise<void> {
    return $Call.ByID(2698353080, nickname);
}

// Private type creation functions
const $$createType0 = vo$0.AccountLevel.createFrom;
const $$createType1 = vo$0.AccountStatus.createFrom;
const $$createType2 = yukihubaccount$0.ChatMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = yukihubaccount$0.ChatEmoji.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = yukihubaccount$0.ChatGroup.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = yukihubaccount$0.FriendList.createFrom;
const $$createType9 = yukihubaccount$0.Friend.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = vo$0.AccountSyncResult.createFrom;
