// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CancelUmbraAuth 取消当前正在等待回调的 Umbra 授权流程。
 */
export function CancelUmbraAuth(): $CancellablePromise<boolean> {
    return $Call.ByID(2311801878);
}

/**
 * CreateAndUploadDBBackup 创建数据库备份并上传到云端
 */
export function CreateAndUploadDBBackup(): $CancellablePromise<vo$0.DBBackupInfo | null> {
    return $Call.ByID(4126157163).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateAndUploadDBBackupForQuit 创建数据库备份并上传到云端（退出流程专用）
 */
export function CreateAndUploadDBBackupForQuit(): $CancellablePromise<vo$0.DBBackupInfo | null> {
    return $Call.ByID(3296568453).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateBackup 创建游戏存档备份
 */
export function CreateBackup(gameID: string): $CancellablePromise<models$0.GameBackup | null> {
    return $Call.ByID(3022703363, gameID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateDBBackup 创建数据库备份（包含 covers 文件夹）
 */
export function CreateDBBackup(): $CancellablePromise<vo$0.DBBackupInfo | null> {
    return $Call.ByID(4206064637).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateFullDataBackup 创建全量数据备份（数据库 + 应用设置 + 数据目录）
 * savePath: 用户选择的保存路径（完整的 .zip 文件路径）
 */
export function CreateFullDataBackup(savePath: string): $CancellablePromise<void> {
    return $Call.ByID(2342486302, savePath);
}

/**
 * DeleteBackup 删除备份（参数改为备份路径）
 */
export function DeleteBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(3686778992, backupPath);
}

/**
 * DeleteDBBackup 删除数据库备份
 */
export function DeleteDBBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(706075218, backupPath);
}

/**
 * DownloadCloudBackup 从云端下载备份
 */
export function DownloadCloudBackup(cloudKey: string, gameID: string): $CancellablePromise<string> {
    return $Call.ByID(427143152, cloudKey, gameID);
}

/**
 * DownloadCloudDBBackup 从云端下载数据库备份
 * TODO: 前端提供此功能的按钮
 */
export function DownloadCloudDBBackup(cloudKey: string): $CancellablePromise<string> {
    return $Call.ByID(4177841618, cloudKey);
}

/**
 * ExchangeOneDriveCode 用授权码换取 OneDrive token
 */
export function ExchangeOneDriveCode(code: string): $CancellablePromise<string> {
    return $Call.ByID(280531933, code);
}

/**
 * GetBackupDir 获取备份根目录
 */
export function GetBackupDir(): $CancellablePromise<string> {
    return $Call.ByID(1082141632);
}

/**
 * GetCloudBackupStatus 获取云备份状态
 */
export function GetCloudBackupStatus(): $CancellablePromise<vo$0.CloudBackupStatus> {
    return $Call.ByID(1252855160).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetCloudDBBackups 获取云端数据库备份列表
 */
export function GetCloudDBBackups(): $CancellablePromise<vo$0.CloudBackupItem[]> {
    return $Call.ByID(3368131477).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCloudGameBackups 获取云端游戏备份列表
 */
export function GetCloudGameBackups(gameID: string): $CancellablePromise<vo$0.CloudBackupItem[]> {
    return $Call.ByID(2663020157, gameID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDBBackupDir 获取数据库备份目录
 */
export function GetDBBackupDir(): $CancellablePromise<string> {
    return $Call.ByID(4103478110);
}

/**
 * GetDBBackups 获取数据库备份列表
 */
export function GetDBBackups(): $CancellablePromise<vo$0.DBBackupStatus | null> {
    return $Call.ByID(682911076).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetFullBackupDir 获取全量数据备份目录
 */
export function GetFullBackupDir(): $CancellablePromise<string> {
    return $Call.ByID(2553323071);
}

/**
 * GetGameBackups 获取游戏的备份历史（直接读取文件夹，不使用数据库）
 */
export function GetGameBackups(gameID: string): $CancellablePromise<models$0.GameBackup[]> {
    return $Call.ByID(2696888352, gameID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetOneDriveAuthURL 获取 OneDrive 授权 URL
 */
export function GetOneDriveAuthURL(): $CancellablePromise<string> {
    return $Call.ByID(2488125766);
}

/**
 * GetUmbraUserProfile 获取当前授权的 Umbra 账户与存储空间信息。
 */
export function GetUmbraUserProfile(config: appconf$0.AppConfig): $CancellablePromise<vo$0.UmbraUserProfile | null> {
    return $Call.ByID(2219422648, config).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * LogoutUmbra 撤销 Umbra OAuth 并清除本机加密凭据。
 */
export function LogoutUmbra(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(4261985232, config);
}

/**
 * OpenBackupFolder 打开备份文件夹
 */
export function OpenBackupFolder(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(809366387, gameID);
}

/**
 * RestoreBackup 恢复备份到指定时间点（参数改为备份路径）
 */
export function RestoreBackup(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(898053887, backupPath);
}

/**
 * RestoreFromCloud 从云端恢复备份
 */
export function RestoreFromCloud(cloudKey: string, gameID: string): $CancellablePromise<void> {
    return $Call.ByID(2443634478, cloudKey, gameID);
}

/**
 * ScheduleDBRestore 安排数据库恢复（下次启动时执行）
 */
export function ScheduleDBRestore(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(1527192336, backupPath);
}

/**
 * ScheduleDBRestoreFromCloud 从云端下载并安排数据库恢复
 */
export function ScheduleDBRestoreFromCloud(cloudKey: string): $CancellablePromise<void> {
    return $Call.ByID(1903410193, cloudKey);
}

/**
 * ScheduleFullDataRestore 安排全量数据恢复（下次启动时执行）
 * backupPath: 用户选择的备份文件完整路径
 */
export function ScheduleFullDataRestore(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(2374721969, backupPath);
}

/**
 * SelectBackupRestorePath 选择要恢复的全量备份文件
 */
export function SelectBackupRestorePath(): $CancellablePromise<string> {
    return $Call.ByID(1612682428);
}

/**
 * SelectBackupSavePath 选择全量备份保存路径
 */
export function SelectBackupSavePath(): $CancellablePromise<string> {
    return $Call.ByID(189037661);
}

/**
 * SetupCloudBackup 设置云备份密码（只能设置一次）
 */
export function SetupCloudBackup(password: string): $CancellablePromise<string> {
    return $Call.ByID(1069058669, password);
}

/**
 * StartOneDriveAuth 启动 OneDrive 授权流程（使用本地回调服务器）
 */
export function StartOneDriveAuth(clientID: string): $CancellablePromise<string> {
    return $Call.ByID(2540112237, clientID);
}

/**
 * StartUmbraAuth 启动 Umbra OAuth 与设备注册流程。
 * OAuth client ID 与安装令牌由发行构建注入，不接受用户手动填写。
 */
export function StartUmbraAuth(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(1207138402, config);
}

/**
 * TestOneDriveConnection 测试 OneDrive 连接
 */
export function TestOneDriveConnection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(1002022997, config);
}

/**
 * TestS3Connection 测试 S3 连接
 */
export function TestS3Connection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(577967583, config);
}

/**
 * TestUmbraConnection 测试 Umbra OAuth、设备签名与备份 API。
 */
export function TestUmbraConnection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(1322001178, config);
}

/**
 * TestWebDAVConnection 测试 WebDAV 连接
 */
export function TestWebDAVConnection(config: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(1816400480, config);
}

/**
 * UploadDBBackupToCloud 上传数据库备份到云端
 */
export function UploadDBBackupToCloud(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(723985718, backupPath);
}

/**
 * UploadGameBackupToCloud 上传游戏存档到云端（参数改为 backupPath）
 */
export function UploadGameBackupToCloud(gameID: string, backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(115710222, gameID, backupPath);
}

// Private type creation functions
const $$createType0 = vo$0.DBBackupInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.GameBackup.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = vo$0.CloudBackupStatus.createFrom;
const $$createType5 = vo$0.CloudBackupItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = vo$0.DBBackupStatus.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType2);
const $$createType10 = vo$0.UmbraUserProfile.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
