// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function AddCategory(name: string, emoji: string): $CancellablePromise<void> {
    return $Call.ByID(4002515730, name, emoji);
}

export function AddGameToCategory(gameID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(1802483149, gameID, categoryID);
}

export function AddGamesToCategories(gameIDs: string[], categoryIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(584812412, gameIDs, categoryIDs);
}

export function DeleteCategories(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(2813888768, ids);
}

export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(1669073908, id);
}

export function GetCategories(): $CancellablePromise<vo$0.CategoryVO[]> {
    return $Call.ByID(40752617).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCategoriesByGame(gameID: string): $CancellablePromise<vo$0.CategoryVO[]> {
    return $Call.ByID(1609682474, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCategoryByID(id: string): $CancellablePromise<vo$0.CategoryVO> {
    return $Call.ByID(2373074057, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCategoryGames(req: vo$0.CategoryGameListRequest): $CancellablePromise<vo$0.GameListResponse> {
    return $Call.ByID(30108332, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGamesByCategory(categoryID: string): $CancellablePromise<models$0.Game[]> {
    return $Call.ByID(1976290905, categoryID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RemoveGameFromCategory(gameID: string, categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(3079862373, gameID, categoryID);
}

export function RemoveGamesFromCategory(gameIDs: string[], categoryID: string): $CancellablePromise<void> {
    return $Call.ByID(329596186, gameIDs, categoryID);
}

export function SearchCategoryGameCandidates(req: vo$0.CategoryGameCandidateRequest): $CancellablePromise<vo$0.GameListResponse> {
    return $Call.ByID(1827994831, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateCategory(id: string, name: string, emoji: string): $CancellablePromise<void> {
    return $Call.ByID(1359372518, id, name, emoji);
}

// Private type creation functions
const $$createType0 = vo$0.CategoryVO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = vo$0.GameListResponse.createFrom;
const $$createType3 = models$0.Game.createFrom;
const $$createType4 = $Create.Array($$createType3);
