// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appconf$0 from "../appconf/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyGameLibraryPathChange(newPath: string, syncPaths: boolean): $CancellablePromise<$models.GameLibraryPathChangeResult> {
    return $Call.ByID(3720449595, newPath, syncPaths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearBigScreenIntroVideo 恢复内置入场动画：删掉受管视频文件并清空配置字段。
 */
export function ClearBigScreenIntroVideo(): $CancellablePromise<void> {
    return $Call.ByID(1070385261);
}

/**
 * ExportLogsZip 将 logs 目录导出为 ZIP 压缩包。
 */
export function ExportLogsZip(): $CancellablePromise<string> {
    return $Call.ByID(3359730563);
}

export function GetAppConfig(): $CancellablePromise<appconf$0.AppConfig> {
    return $Call.ByID(2829845904).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenDataDirectory 在系统文件管理器中打开 YukiHub 数据目录。
 */
export function OpenDataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2324380672);
}

export function PreviewGameLibraryPathChange(newPath: string): $CancellablePromise<$models.GameLibraryPathChangePreview> {
    return $Call.ByID(3507124007, newPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SafeQuit 安全退出应用（绕过托盘最小化逻辑）
 */
export function SafeQuit(): $CancellablePromise<void> {
    return $Call.ByID(3067098483);
}

/**
 * SaveCroppedBackgroundImage 保存裁剪后的背景图片
 * srcPath 应为 /local/backgrounds/temp_bg_xxx.png 格式的路径
 */
export function SaveCroppedBackgroundImage(srcPath: string, x: number, y: number, width: number, height: number): $CancellablePromise<string> {
    return $Call.ByID(2250148296, srcPath, x, y, width, height);
}

/**
 * SelectAndCropBackgroundImage 打开文件选择对话框选择背景图片，复制到临时目录并返回 /local/ 路径供前端裁剪
 */
export function SelectAndCropBackgroundImage(): $CancellablePromise<string> {
    return $Call.ByID(3605670101);
}

/**
 * SelectBackgroundImage 打开文件选择对话框选择背景图片，并保存到应用目录
 */
export function SelectBackgroundImage(): $CancellablePromise<string> {
    return $Call.ByID(2037683390);
}

/**
 * SelectBigScreenIntroVideo 选择大屏入场视频：复制进受管目录并写入
 * `bigscreen_intro_video`（对齐手机端 M18-2 的 bigscreen_intro_video）。
 * 返回 /local/intro/... 地址；用户取消时返回空串且不报错。
 */
export function SelectBigScreenIntroVideo(): $CancellablePromise<string> {
    return $Call.ByID(2911546604);
}

/**
 * SelectDirectory 打开目录选择对话框
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(145890116, title);
}

export function ShouldShowMainWindowOnReady(): $CancellablePromise<boolean> {
    return $Call.ByID(2939380254);
}

export function UpdateAppConfig(newConfig: appconf$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(917175337, newConfig);
}

// Private type creation functions
const $$createType0 = $models.GameLibraryPathChangeResult.createFrom;
const $$createType1 = appconf$0.AppConfig.createFrom;
const $$createType2 = $models.GameLibraryPathChangePreview.createFrom;
