// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enums$0 from "../common/enums/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchImportGames 批量导入游戏
 */
export function BatchImportGames(candidates: vo$0.BatchImportCandidate[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3799739794, candidates).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CheckImportMetadataDuplicates 批量检查元数据 source/id 是否已存在。
 */
export function CheckImportMetadataDuplicates(requests: vo$0.ImportMetadataDuplicateRequest[]): $CancellablePromise<vo$0.ImportMetadataDuplicateResult[]> {
    return $Call.ByID(3023356412, requests).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ExportToYukiHub 把桌面端库导出为 YukiHub schema 5 备份（.ykbak），手机版可直接导入。
 * 
 * 与导入方向对称：导出完成后会把「多少个游戏 / 多少条游玩记录」回报给调用方，
 * 前端好提示用户。契约细节见 docs/mobile-yukihub-migration.md。
 */
export function ExportToYukiHub(path: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1445061962, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchMetadataForCandidate 为单个候选项获取元数据（带限流）
 */
export function FetchMetadataForCandidate(searchName: string): $CancellablePromise<vo$0.BatchImportCandidate> {
    return $Call.ByID(3254766843, searchName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FetchMetadataForCandidateWithPreference fetches and filters metadata for bulk import.
 * A configured preferred source is authoritative. Without one, the search name is
 * used as the reference for every enabled source.
 */
export function FetchMetadataForCandidateWithPreference(searchName: string, preferredSource: enums$0.SourceType): $CancellablePromise<vo$0.BatchImportMetadataMatchResult> {
    return $Call.ByID(2130067174, searchName, preferredSource).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ImportFromLunaBox 从上游 LunaBox 备份导入游戏与游玩记录。
 */
export function ImportFromLunaBox(zipPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3701756226, zipPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromLunaBoxWithOptions 按同名路径处理策略导入 LunaBox 数据。
 */
export function ImportFromLunaBoxWithOptions(zipPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(239242528, zipPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromLunaBoxWithSelection 只导入 LunaBox 备份里被选中的条目。
 */
export function ImportFromLunaBoxWithSelection(zipPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2705419384, zipPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromPlaynite 从 Playnite 导出的 JSON 文件导入数据
 */
export function ImportFromPlaynite(jsonPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1722603939, jsonPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPlayniteWithOptions(jsonPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2510264655, jsonPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPlayniteWithSelection(jsonPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1136602975, jsonPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromPotatoVN 从 PotatoVN 导出的 ZIP 文件导入数据
 */
export function ImportFromPotatoVN(zipPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1797603728, zipPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPotatoVNWithOptions(zipPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1933769878, zipPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromPotatoVNWithSelection(zipPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1350935398, zipPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromReinaManager 从 ReinaManager SQLite 数据库备份导入数据。
 */
export function ImportFromReinaManager(dbPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3979779183, dbPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromReinaManagerWithOptions(dbPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1017010595, dbPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromReinaManagerWithSelection(dbPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2469669747, dbPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromSteamLocal 从本机 Steam 库导入已安装游戏。
 */
export function ImportFromSteamLocal(skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(4290077536, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromSteamLocalWithOptions(skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(688352614, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromSteamLocalWithSelection(skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(780248342, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromVnite 从 Vnite 导出的数据库目录导入数据
 */
export function ImportFromVnite(vniteDir: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1000579021, vniteDir, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromVniteWithOptions(vniteDir: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(853057033, vniteDir, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromVniteWithSelection(vniteDir: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1283728713, vniteDir, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFromYukiHub 从 YukiHub 备份导入游戏与游玩记录。
 */
export function ImportFromYukiHub(backupPath: string, skipNoPath: boolean): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1863276104, backupPath, skipNoPath).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromYukiHubWithOptions(backupPath: string, skipNoPath: boolean, samePathAction: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3463872286, backupPath, skipNoPath, samePathAction).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ImportFromYukiHubWithSelection(backupPath: string, skipNoPath: boolean, samePathAction: string, selections: vo$0.ImportSelection[]): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3373703918, backupPath, skipNoPath, samePathAction, selections).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PreviewImport 预览 PotatoVN 导入内容（不实际导入）
 */
export function PreviewImport(zipPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(507045495, zipPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewLunaBoxImport 预览 LunaBox 备份中的游戏。
 */
export function PreviewLunaBoxImport(zipPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(2556415936, zipPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewPlayniteImport 预览 Playnite 导入内容（不实际导入）
 */
export function PreviewPlayniteImport(jsonPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(2104232847, jsonPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewReinaManagerImport 预览 ReinaManager 数据库备份中的游戏。
 */
export function PreviewReinaManagerImport(dbPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(1751137987, dbPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewSteamLocalImport 扫描本机已安装 Steam 游戏并预览导入内容。
 */
export function PreviewSteamLocalImport(): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(1021271472).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewVniteImport 预览 Vnite 导入内容（不实际导入）
 */
export function PreviewVniteImport(vniteDir: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(1185164399, vniteDir).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * PreviewYukiHubImport 预览 YukiHub 备份中的游戏。
 */
export function PreviewYukiHubImport(backupPath: string): $CancellablePromise<$models.PreviewGame[]> {
    return $Call.ByID(1415542562, backupPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ProcessDroppedPaths 处理拖拽导入的路径，支持文件夹和可执行文件
 * 返回候选游戏列表供前端展示和确认
 */
export function ProcessDroppedPaths(paths: string[]): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(321094969, paths).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ProcessDroppedPathsWithOptions 处理拖拽导入的路径，并复用批量导入的扫描命名选项。
 */
export function ProcessDroppedPathsWithOptions(paths: string[], options: vo$0.BatchImportScanOptions): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(426975613, paths, options).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanLibraryDirectory 扫描游戏库目录，返回默认待导入候选项和路径阶段跳过项。
 */
export function ScanLibraryDirectory(libraryPath: string): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(2192617837, libraryPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ScanLibraryDirectoryWithOptions 按指定模式扫描游戏库目录。
 */
export function ScanLibraryDirectoryWithOptions(libraryPath: string, options: vo$0.BatchImportScanOptions): $CancellablePromise<vo$0.BatchImportScanResult> {
    return $Call.ByID(3462014889, libraryPath, options).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SelectJSONFile 选择要导入的 JSON 文件
 */
export function SelectJSONFile(): $CancellablePromise<string> {
    return $Call.ByID(1235757262);
}

/**
 * SelectLibraryDirectory 选择游戏库目录，并仅将当前系统可访问的目录用于初始化对话框。
 */
export function SelectLibraryDirectory(initialDirectory: string): $CancellablePromise<$models.LibraryDirectorySelection> {
    return $Call.ByID(675902908, initialDirectory).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SelectLunaBoxBackup 选择上游 LunaBox 的 ZIP 备份文件。
 * 
 * LunaBox 的备份是 ZIP（默认落在 %APPDATA%\LunaBox\backups\database\），
 * 对话框存在该目录时直接以它为起始目录。
 */
export function SelectLunaBoxBackup(): $CancellablePromise<string> {
    return $Call.ByID(3168666687);
}

/**
 * SelectReinaManagerDatabase 选择 ReinaManager 导出的 SQLite 数据库备份。
 */
export function SelectReinaManagerDatabase(): $CancellablePromise<string> {
    return $Call.ByID(4226037823);
}

/**
 * SelectVniteDirectory 选择 Vnite 导出的数据库目录
 */
export function SelectVniteDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2993686053);
}

/**
 * SelectYukiHubBackup 选择 YukiHub 导出的备份文件。
 */
export function SelectYukiHubBackup(): $CancellablePromise<string> {
    return $Call.ByID(3404693645);
}

/**
 * SelectYukiHubExportPath 选择 YukiHub 备份的保存位置。
 * 
 * 对手是手机版：文件名沿用手机版的 `yukihub_backup_<毫秒时间戳>.ykbak`，
 * 这样用户在两端看到的是同一套命名。
 */
export function SelectYukiHubExportPath(): $CancellablePromise<string> {
    return $Call.ByID(2321192534);
}

/**
 * SelectZipFile 选择要导入的 ZIP 文件
 */
export function SelectZipFile(): $CancellablePromise<string> {
    return $Call.ByID(1685332107);
}

// Private type creation functions
const $$createType0 = $models.ImportResult.createFrom;
const $$createType1 = vo$0.ImportMetadataDuplicateResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = vo$0.BatchImportCandidate.createFrom;
const $$createType4 = vo$0.BatchImportMetadataMatchResult.createFrom;
const $$createType5 = $models.PreviewGame.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = vo$0.BatchImportScanResult.createFrom;
const $$createType8 = $models.LibraryDirectorySelection.createFrom;
