// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BatchImportGamesToSteam(gameIDs: string[]): $CancellablePromise<$models.SteamBatchImportResult> {
    return $Call.ByID(297544880, gameIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetGameSteamStatus(gameID: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(596984333, gameID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportGameToSteam(gameID: string): $CancellablePromise<$models.SteamImportResult> {
    return $Call.ByID(3268789273, gameID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetGameSteamLaunchOptions(gameID: string, launchOptions: string): $CancellablePromise<$models.SteamLaunchStatus> {
    return $Call.ByID(1395297278, gameID, launchOptions).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SteamBatchImportResult.createFrom;
const $$createType1 = $models.SteamLaunchStatus.createFrom;
const $$createType2 = $models.SteamImportResult.createFrom;
