// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NextMoeService 负责 NextMoe 授权链路与用户令牌的存取刷新。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

export function Disconnect(): $CancellablePromise<vo$0.NextMoeAuthStatus> {
    return $Call.ByID(368214377).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAuthStatus(): $CancellablePromise<vo$0.NextMoeAuthStatus> {
    return $Call.ByID(3600607889).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProfile(): $CancellablePromise<vo$0.NextMoeProfile> {
    return $Call.ByID(2421694070).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartAuth(): $CancellablePromise<vo$0.NextMoeAuthStatus> {
    return $Call.ByID(477645691).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = vo$0.NextMoeAuthStatus.createFrom;
const $$createType1 = vo$0.NextMoeProfile.createFrom;
