// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OverlayService 管理「浮层类窗口」：游戏内好友栏（overlay）与好友通知浮层。
 * 
 * 窗口本身由 main.go 持有（它们必须在主线程创建，且属于 Wails 那一层的
 * 细节），这里只负责：快捷键的读写与校验、通知内容的暂存、以及通知被点后
 * 「把用户带回好友面板」。窗口操作通过注入的函数回调完成。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DismissFriendPlayNotice 收起通知浮层（浮层自己倒计时结束时会调用）。
 */
export function DismissFriendPlayNotice(): $CancellablePromise<void> {
    return $Call.ByID(2460966323);
}

/**
 * GetFriendPlayNotice 返回当前待展示的通知；没有则返回 nil。
 * 
 * 通知浮层前端挂载时拉一次：窗口是刚创建/刚 Show 出来的，前端挂载晚于后端
 * 推送，只靠事件会漏掉第一条。
 */
export function GetFriendPlayNotice(): $CancellablePromise<$models.FriendPlayEvent | null> {
    return $Call.ByID(463597527).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetOverlayShortcut 返回当前快捷键的配置值与实际生效值。
 */
export function GetOverlayShortcut(): $CancellablePromise<vo$0.OverlayShortcut> {
    return $Call.ByID(3931290757).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenFriendsPanel 把用户带回好友面板：恢复主窗口 + 让界面展开好友面板。
 * 
 * 通知浮层被点击时调用（对齐 Steam：点通知打开好友列表）。
 */
export function OpenFriendsPanel(): $CancellablePromise<void> {
    return $Call.ByID(938105810);
}

/**
 * ResetOverlayShortcut 恢复默认快捷键。
 */
export function ResetOverlayShortcut(): $CancellablePromise<vo$0.OverlayShortcut> {
    return $Call.ByID(427500376).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetOverlayShortcut 改快捷键：先真的注册成功，再写进配置。
 * 
 * 顺序不能反 —— 反了的话，注册失败（被别的程序占用）也已经把配置改了，
 * 下次启动就会用一个注册不上的组合。
 */
export function SetOverlayShortcut(accelerator: string): $CancellablePromise<vo$0.OverlayShortcut> {
    return $Call.ByID(1920659289, accelerator).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ToggleFriendsOverlay 呼出/收起好友栏（供设置页的「试一下」按钮使用）。
 */
export function ToggleFriendsOverlay(): $CancellablePromise<void> {
    return $Call.ByID(3093611324);
}

// Private type creation functions
const $$createType0 = $models.FriendPlayEvent.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = vo$0.OverlayShortcut.createFrom;
