// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortableSetupService exposes setup helpers needed by portable and AppImage
 * builds. Packaged installer builds receive their custom URL protocol
 * association from Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetStatus returns the portable yukihub:// protocol registration state.
 */
export function GetStatus(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(1196311803).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RegisterProtocol writes the yukihub:// association required by local builds.
 * Installed builds are managed by Wails during packaging.
 */
export function RegisterProtocol(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(854825170).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UnregisterProtocol removes the current-user association created for a local
 * build.
 */
export function UnregisterProtocol(): $CancellablePromise<$models.PortableSetupStatus> {
    return $Call.ByID(351153089).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PortableSetupStatus.createFrom;
