// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SelfSyncService 把与手机版**完全相同**的 schema 5 快照同步到用户自建的 WebDAV，
 * 对应手机版 SyncManager 的 `sync()`。
 * 
 * 与「账号云同步」（yukihub.zh.kg）的区别只在传输通道：快照的构造、导入语义、
 * 冲突判定全部共用同一份实现（buildYukiHubSnapshot / importYukiHubSnapshot），
 * 所以两边同步出去的数据必须一致 —— 这是「传给云端的数据要和手机版一致」的前提。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../common/vo/models.js";

/**
 * GetSelfSyncConfig 回显 WebDAV 配置（含密码，手机版同样把密码填回输入框）。
 */
export function GetSelfSyncConfig(): $CancellablePromise<vo$0.SelfSyncConfig> {
    return $Call.ByID(1446050137).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RunStartupSelfSync 启动时的自动同步：已配置 + 开了自动同步 + 距上次超过 10 分钟
 * 才跑；冲突按手机版 maybeAutoWebDavSync 的做法默认「智能合并」。
 */
export function RunStartupSelfSync(): $CancellablePromise<void> {
    return $Call.ByID(3715257261);
}

/**
 * SaveSelfSyncConfig 保存 WebDAV 配置。
 * 
 * 校验规则与手机版 WebDavSettingsDialog.saveConfig 一致：三项都必填，
 * 地址缺协议头时自动补 `https://`（坚果云等只接受 https）。
 */
export function SaveSelfSyncConfig(cfg: vo$0.SelfSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(1956976400, cfg);
}

/**
 * SyncSelfHostedNow 立刻与 WebDAV 同步一次。
 * 
 * resolution 为空时：若判定为冲突，**不擅自合并**，而是返回 Action=conflict 与
 * 两侧字节数，交由界面询问用户（对齐手机版 WebDavSettingsDialog 的冲突对话框）。
 * 用户选完后再带 resolution 调一次：merge / local / remote / cancel。
 */
export function SyncSelfHostedNow(resolution: string): $CancellablePromise<vo$0.SelfSyncResult> {
    return $Call.ByID(462295668, resolution).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestSelfSyncConnection 用**表单里的**配置测一次连通性，不影响已保存的配置。
 */
export function TestSelfSyncConnection(cfg: vo$0.SelfSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(3922659207, cfg);
}

// Private type creation functions
const $$createType0 = vo$0.SelfSyncConfig.createFrom;
const $$createType1 = vo$0.SelfSyncResult.createFrom;
