// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetBuildMode 返回构建模式
 */
export function GetBuildMode(): $CancellablePromise<string> {
    return $Call.ByID(153473188);
}

/**
 * GetBuildTime 返回构建时间
 */
export function GetBuildTime(): $CancellablePromise<string> {
    return $Call.ByID(2653118450);
}

/**
 * GetFullVersion 返回完整版本信息
 */
export function GetFullVersion(): $CancellablePromise<string> {
    return $Call.ByID(3869880536);
}

/**
 * GetGOOS 返回当前运行平台。
 */
export function GetGOOS(): $CancellablePromise<string> {
    return $Call.ByID(1753739893);
}

/**
 * GetVersion 返回版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3660551071);
}

/**
 * GetVersionInfo 返回版本信息对象
 */
export function GetVersionInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4024408811).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SupportsBackgroundProcessMute reports whether the running operating system
 * provides the per-process audio controls required by background game mute.
 */
export function SupportsBackgroundProcessMute(): $CancellablePromise<boolean> {
    return $Call.ByID(2438934921);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
