//go:build !windows

package apputils

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

const CLIExecutableName = "lunacli"
const appImageCLIWrapperMarker = "# Generated by LunaBox AppImage CLI integration."

func getCLIDir() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve executable path: %w", err)
	}
	abs, err := filepath.Abs(exe)
	if err != nil {
		return "", fmt.Errorf("resolve absolute executable path: %w", err)
	}
	if runtime.GOOS == "darwin" {
		const bundleMarker = ".app/Contents/MacOS/"
		if idx := strings.Index(abs, bundleMarker); idx >= 0 {
			return filepath.Join(abs[:idx+len(".app")], "Contents", "Resources", "bin"), nil
		}
	}
	return filepath.Dir(abs), nil
}

func GetCLIInstallPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home directory: %w", err)
	}
	return filepath.Join(home, ".local", "bin", CLIExecutableName), nil
}

func IsCLIInstalled() (bool, error) {
	target, err := GetCLIInstallPath()
	if err != nil {
		return false, err
	}

	if IsAppImageMode() {
		return isAppImageCLIWrapperInstalled(target)
	}

	source, err := GetCLIPath()
	if err != nil {
		return false, err
	}

	resolved, err := os.Readlink(target)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read CLI symlink: %w", err)
	}
	if !filepath.IsAbs(resolved) {
		resolved = filepath.Join(filepath.Dir(target), resolved)
	}
	resolved, _ = filepath.Abs(resolved)
	source, _ = filepath.Abs(source)
	return resolved == source, nil
}

func InstallCLI() (bool, error) {
	if IsAppImageMode() {
		return installAppImageCLIWrapper()
	}

	source, err := GetCLIPath()
	if err != nil {
		return false, err
	}
	target, err := GetCLIInstallPath()
	if err != nil {
		return false, err
	}

	if info, err := os.Stat(source); err != nil {
		if os.IsNotExist(err) {
			return false, fmt.Errorf("CLI binary does not exist: %s", source)
		}
		return false, fmt.Errorf("stat CLI binary: %w", err)
	} else if info.IsDir() {
		return false, fmt.Errorf("CLI binary path is a directory: %s", source)
	}

	installed, err := IsCLIInstalled()
	if err != nil {
		return false, err
	}
	if installed {
		return false, nil
	}

	if existing, err := os.Lstat(target); err == nil {
		if existing.Mode()&os.ModeSymlink == 0 {
			return false, fmt.Errorf("CLI install target already exists and is not a symlink: %s", target)
		}
		if err := os.Remove(target); err != nil {
			return false, fmt.Errorf("remove stale CLI symlink: %w", err)
		}
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat CLI install target: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return false, fmt.Errorf("create CLI install directory: %w", err)
	}
	if err := os.Symlink(source, target); err != nil {
		return false, fmt.Errorf("create CLI symlink: %w", err)
	}
	return true, nil
}

func UninstallCLI() (bool, error) {
	if IsAppImageMode() {
		return uninstallAppImageCLIWrapper()
	}

	target, err := GetCLIInstallPath()
	if err != nil {
		return false, err
	}
	info, err := os.Lstat(target)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("stat CLI install target: %w", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return false, fmt.Errorf("CLI install target is not a symlink: %s", target)
	}
	if err := os.Remove(target); err != nil {
		return false, fmt.Errorf("remove CLI symlink: %w", err)
	}
	return true, nil
}

func IsDirInUserPath(_ string) (bool, error) {
	return false, nil
}

func AddDirToUserPath(_ string) (bool, error) {
	return false, fmt.Errorf("PATH editing is only supported on Windows")
}

func RemoveDirFromUserPath(_ string) (bool, error) {
	return false, fmt.Errorf("PATH editing is only supported on Windows")
}

func isAppImageCLIWrapperInstalled(target string) (bool, error) {
	appImagePath, err := GetAppImagePath()
	if err != nil {
		return false, nil
	}

	content, err := os.ReadFile(target)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read CLI wrapper: %w", err)
	}
	return string(content) == appImageCLIWrapperContent(appImagePath), nil
}

func installAppImageCLIWrapper() (bool, error) {
	appImagePath, err := GetAppImagePath()
	if err != nil {
		return false, err
	}
	target, err := GetCLIInstallPath()
	if err != nil {
		return false, err
	}

	expected := appImageCLIWrapperContent(appImagePath)
	if content, err := os.ReadFile(target); err == nil && string(content) == expected {
		return false, nil
	}

	if existing, err := os.Lstat(target); err == nil {
		if existing.Mode()&os.ModeSymlink != 0 {
			if err := os.Remove(target); err != nil {
				return false, fmt.Errorf("remove stale CLI symlink: %w", err)
			}
		} else {
			content, readErr := os.ReadFile(target)
			if readErr != nil {
				return false, fmt.Errorf("read existing CLI install target: %w", readErr)
			}
			if !strings.Contains(string(content), appImageCLIWrapperMarker) {
				return false, fmt.Errorf("CLI install target already exists and was not created by LunaBox: %s", target)
			}
			if err := os.Remove(target); err != nil {
				return false, fmt.Errorf("remove stale CLI wrapper: %w", err)
			}
		}
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat CLI install target: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return false, fmt.Errorf("create CLI install directory: %w", err)
	}
	if err := os.WriteFile(target, []byte(expected), 0755); err != nil {
		return false, fmt.Errorf("write CLI wrapper: %w", err)
	}
	return true, nil
}

func uninstallAppImageCLIWrapper() (bool, error) {
	target, err := GetCLIInstallPath()
	if err != nil {
		return false, err
	}
	info, err := os.Lstat(target)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("stat CLI install target: %w", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		content, err := os.ReadFile(target)
		if err != nil {
			return false, fmt.Errorf("read CLI install target: %w", err)
		}
		if !strings.Contains(string(content), appImageCLIWrapperMarker) {
			return false, fmt.Errorf("CLI install target was not created by LunaBox: %s", target)
		}
	}
	if err := os.Remove(target); err != nil {
		return false, fmt.Errorf("remove CLI install target: %w", err)
	}
	return true, nil
}

func appImageCLIWrapperContent(appImagePath string) string {
	return strings.Join([]string{
		"#!/usr/bin/env sh",
		appImageCLIWrapperMarker,
		"exec " + shellSingleQuote(appImagePath) + ` cli "$@"`,
		"",
	}, "\n")
}

func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}
