//go:build linux

package protocol

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	linuxDesktopID              = "io.github.saramanda9988.lunabox"
	linuxDesktopFileName        = linuxDesktopID + ".desktop"
	linuxAppImageLauncherName   = "appimage-launcher"
	linuxAppImageLauncherMarker = "# Generated by LunaBox AppImage protocol integration."
)

var legacyLinuxDesktopFileNames = []string{
	"org.wails.lunabox.desktop",
	"lunabox.desktop",
}

func RegisterURLScheme(exePath string) error {
	if strings.TrimSpace(exePath) == "" {
		var err error
		exePath, err = os.Executable()
		if err != nil {
			return fmt.Errorf("get executable path: %w", err)
		}
	}
	exePath, err := filepath.Abs(filepath.Clean(exePath))
	if err != nil {
		return fmt.Errorf("normalize executable path: %w", err)
	}
	protocolExePath := exePath
	if isAppImagePath(exePath) {
		protocolExePath, err = installAppImageProtocolLauncher(exePath)
		if err != nil {
			return err
		}
	}

	desktopPath, err := userDesktopFilePath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(desktopPath), 0755); err != nil {
		return fmt.Errorf("create applications directory: %w", err)
	}
	if err := os.WriteFile(desktopPath, []byte(protocolDesktopEntry(protocolExePath)), 0644); err != nil {
		return fmt.Errorf("write desktop entry: %w", err)
	}
	removeLegacyDesktopFile(desktopPath)

	if xdgMime, err := exec.LookPath("xdg-mime"); err == nil {
		if err := exec.Command(xdgMime, "default", linuxDesktopFileName, "x-scheme-handler/"+Scheme).Run(); err != nil {
			return fmt.Errorf("register xdg mime handler: %w", err)
		}
	} else {
		return fmt.Errorf("xdg-mime not found; install xdg-utils to register %s://", Scheme)
	}
	refreshDesktopDatabase(filepath.Dir(desktopPath))
	return nil
}

func RegisterPortableURLScheme(exePath string) error {
	return RegisterURLScheme(exePath)
}

func UnregisterURLScheme() error {
	applicationsDir, err := userApplicationsDir()
	if err != nil {
		return err
	}
	for _, desktopFileName := range append([]string{linuxDesktopFileName}, legacyLinuxDesktopFileNames...) {
		path := filepath.Join(applicationsDir, desktopFileName)
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove desktop entry: %w", err)
		}
	}
	refreshDesktopDatabase(applicationsDir)
	return nil
}

func UnregisterPortableURLScheme() error {
	return UnregisterURLScheme()
}

func GetRegisteredURLSchemeExe() (string, error) {
	xdgMime, err := exec.LookPath("xdg-mime")
	if err != nil {
		return "", nil
	}
	out, err := exec.Command(xdgMime, "query", "default", "x-scheme-handler/"+Scheme).Output()
	if err != nil {
		return "", nil
	}
	desktopName := strings.TrimSpace(string(out))
	if desktopName == "" {
		return "", nil
	}

	for _, candidate := range desktopFileCandidates(desktopName) {
		exe, err := execFromDesktopFile(candidate)
		if err == nil && strings.TrimSpace(exe) != "" {
			return exe, nil
		}
	}
	return "", nil
}

func userDesktopFilePath() (string, error) {
	applicationsDir, err := userApplicationsDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(applicationsDir, linuxDesktopFileName), nil
}

func userApplicationsDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get user home: %w", err)
	}
	return filepath.Join(home, ".local", "share", "applications"), nil
}

func protocolDesktopEntry(exePath string) string {
	icon := protocolDesktopIcon(exePath)
	return strings.Join([]string{
		"[Desktop Entry]",
		"Version=1.0",
		"Type=Application",
		"Name=LunaBox",
		"Comment=LunaBox game library manager",
		"Exec=" + quoteDesktopExecArg(exePath) + " %u",
		"Terminal=false",
		"Icon=" + icon,
		"Categories=Game;",
		"StartupWMClass=" + linuxDesktopID,
		"MimeType=x-scheme-handler/" + Scheme + ";",
		"",
	}, "\n")
}

func protocolDesktopIcon(exePath string) string {
	portableIcon := filepath.Join(filepath.Dir(exePath), "appicon.png")
	if info, err := os.Stat(portableIcon); err == nil && !info.IsDir() {
		return portableIcon
	}
	return linuxDesktopID
}

// isAppImageProtocolLauncher reports whether path is LunaBox's generated
// AppImage protocol launcher. It is used to distinguish our stable wrapper from
// real package-managed executables such as /usr/bin/LunaBox.
func isAppImageProtocolLauncher(path string) bool {
	content, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(content), linuxAppImageLauncherMarker)
}

// isAppImageProtocolLauncherFor reports whether path is the generated AppImage
// protocol launcher for the given AppImage file.
func isAppImageProtocolLauncherFor(path string, appImagePath string) bool {
	content, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	expected, err := appImageProtocolLauncherContent(appImagePath)
	if err != nil {
		return false
	}
	return string(content) == expected
}

// platformHandlerMatchesTarget treats LunaBox's stable AppImage launcher as an
// equivalent registration for the AppImage it wraps.
func platformHandlerMatchesTarget(registeredPath string, targetPath string) bool {
	return isAppImageProtocolLauncherFor(registeredPath, targetPath)
}

// platformManagedHandler reports LunaBox-created handlers: the generated
// AppImage launcher and AppImage files registered directly by older builds.
func platformManagedHandler(registeredPath string) bool {
	return isAppImageProtocolLauncher(registeredPath) || isAppImagePath(registeredPath)
}

func isAppImagePath(path string) bool {
	return strings.EqualFold(filepath.Ext(strings.TrimSpace(path)), ".AppImage")
}

func installAppImageProtocolLauncher(appImagePath string) (string, error) {
	target, err := appImageProtocolLauncherPath()
	if err != nil {
		return "", err
	}
	content, err := appImageProtocolLauncherContent(appImagePath)
	if err != nil {
		return "", err
	}

	if existing, err := os.Lstat(target); err == nil {
		if existing.IsDir() {
			return "", fmt.Errorf("AppImage protocol launcher target is a directory: %s", target)
		}
		if existing.Mode()&os.ModeSymlink != 0 {
			if err := os.Remove(target); err != nil {
				return "", fmt.Errorf("remove stale AppImage protocol launcher symlink: %w", err)
			}
		} else if !isAppImageProtocolLauncher(target) {
			return "", fmt.Errorf("AppImage protocol launcher target already exists and was not created by LunaBox: %s", target)
		}
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("stat AppImage protocol launcher: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return "", fmt.Errorf("create AppImage protocol launcher directory: %w", err)
	}
	if err := os.WriteFile(target, []byte(content), 0755); err != nil {
		return "", fmt.Errorf("write AppImage protocol launcher: %w", err)
	}
	return target, nil
}

func appImageProtocolLauncherPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get user home: %w", err)
	}
	return filepath.Join(home, ".local", "share", "LunaBox", linuxAppImageLauncherName), nil
}

func appImageProtocolLauncherContent(appImagePath string) (string, error) {
	appImagePath, err := filepath.Abs(filepath.Clean(appImagePath))
	if err != nil {
		return "", fmt.Errorf("normalize AppImage path: %w", err)
	}
	return strings.Join([]string{
		"#!/usr/bin/env sh",
		linuxAppImageLauncherMarker,
		"set -eu",
		"appimage=" + shellSingleQuote(appImagePath),
		`if [ -x "$appimage" ]; then`,
		`    exec "$appimage" "$@"`,
		"fi",
		`home_dir="${HOME:-}"`,
		`if [ -n "$home_dir" ]; then`,
		`    latest="$(find "$home_dir/Downloads" "$home_dir/下载" "$home_dir/Applications" "$home_dir/.local/bin" -maxdepth 4 -type f -name 'LunaBox-*-linux-*.AppImage' -perm -u=x -printf '%T@ %p\n' 2>/dev/null | sort -nr | sed -n '1s/^[^ ]* //p')"`,
		`    if [ -n "$latest" ] && [ -x "$latest" ]; then`,
		`        exec "$latest" "$@"`,
		"    fi",
		"fi",
		`echo "LunaBox AppImage not found: $appimage" >&2`,
		"exit 127",
		"",
	}, "\n"), nil
}

func removeLegacyDesktopFile(currentDesktopPath string) {
	for _, desktopFileName := range legacyLinuxDesktopFileNames {
		legacyPath := filepath.Join(filepath.Dir(currentDesktopPath), desktopFileName)
		if legacyPath != currentDesktopPath {
			_ = os.Remove(legacyPath)
		}
	}
}

func desktopFileCandidates(name string) []string {
	candidates := make([]string, 0, 4)
	if filepath.IsAbs(name) {
		return append(candidates, name)
	}
	if userPath, err := userDesktopFilePath(); err == nil && filepath.Base(userPath) == name {
		candidates = append(candidates, userPath)
	}
	home, err := os.UserHomeDir()
	if err == nil {
		candidates = append(candidates, filepath.Join(home, ".local", "share", "applications", name))
	}
	candidates = append(candidates, filepath.Join("/usr/share/applications", name))
	return candidates
}

func execFromDesktopFile(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "Exec=") {
			continue
		}
		return extractDesktopExecPath(strings.TrimPrefix(line, "Exec=")), nil
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", nil
}

func extractDesktopExecPath(command string) string {
	command = strings.TrimSpace(stripDesktopFieldCodes(command))
	if command == "" {
		return ""
	}
	if strings.HasPrefix(command, `"`) {
		escaped := false
		var builder strings.Builder
		for _, r := range command[1:] {
			if escaped {
				builder.WriteRune(r)
				escaped = false
				continue
			}
			if r == '\\' {
				escaped = true
				continue
			}
			if r == '"' {
				return builder.String()
			}
			builder.WriteRune(r)
		}
		return builder.String()
	}
	if idx := strings.Index(command, " "); idx >= 0 {
		return command[:idx]
	}
	return command
}

func stripDesktopFieldCodes(command string) string {
	for _, code := range []string{"%u", "%U", "%f", "%F"} {
		command = strings.ReplaceAll(command, code, "")
	}
	return command
}

func quoteDesktopExecArg(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "`", "\\`", "$", "\\$")
	return `"` + replacer.Replace(value) + `"`
}

func shellSingleQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func refreshDesktopDatabase(dir string) {
	if updater, err := exec.LookPath("update-desktop-database"); err == nil {
		_ = exec.Command(updater, dir).Run()
	}
}
